antfu/case-police

dict.json
See https://webpack.js.org/concepts/
=> fix: fix casing for webpack

dict.json
=> feat: add SQLServer

dict.json
=> feat: add LRU

dict.json
=> feat: add AirDrop, iPadOS and watchOS.

dict.json
Adding WordPress in dict.json file
=> feat: add WordPress

dict.json
=> feat: add VMware

dict.json
=> feat: add ROM

dict.json
Add entry for MathML and Mongoose
=> feat: add MathML and Mongoose

dict.json
=> feat: add ReScript

README.md, src/index.ts
=> feat: support custom dict

dict.json
=> feat: add XMind

dict.json
=> feat: add ECharts

dict.json
=> feat: add XaaS

dict.json
=> feat: add mPaaS

dict.json
i'm not that sure if we need DenoDeploy, let me know if changes are needed :)
=> feat: add DenoDeploy, GitBook, MkDocs and FastAPI

dict.json
=> feat: add iMovie

dict.json
=> feat: add Django

dict.json
Add [OpenAPI](https://en.wikipedia.org/wiki/OpenAPI_Specification) to the list
=> feat: Add OpenAPI

dict.json
=> feat: add MATHIEU

CONTRIBUTING.md
Adding is a noun, not something "you" do. To "add up" or "add to" is a verb and is therefore something "you" can actually do.
=> chore: grammar police

dict/products.json, src/utils.ts
Added a new word to the production.json file "macbook pro" -> "MacBook Pro"
=> feat: add macbook pro -> MacBook Pro

dict/abbreviates.json, dict/softwares.json
=> feat: add word "quic"

src/index.ts
=> feat: ignore minified files by default

README.md
This pull request adds [actions-case-police](https://github.com/Namchee/actions-case-police) under Related Projects section.
`actions-case-police` is a port of `case-police` to GitHub actions that correct letter casing on GitHub issues and pull requests.
=> docs: add actions-case-police

dict/abbreviates.json
=> feat: add POSIX

src/index.ts, src/utils.ts, test/dict/utf8.json, test/index.test.ts
#89
sorry for the misunderstanding
this PR focus on 2 parts: 
1. exclude user dictionary form the parsing objects
2. fix issue #89 (may be not correct :) )
=> feat: UTF-8 support

dict/softwares.json
I found the case at https://github.com/denoland/wasmbuild/blob/a8aa43dc50ca5944e1487d83bdfaf9e7231e21b2/lib/commands/build_command.ts#L26
=> feat: add "web assembly"

dict/brands.json
=> feat: add Gitea

dict/softwares.json
Hi @antfu ! 👋 Thanks for this project, really cool!
Quick PR to add `webpack`, since I see this commonly cased as `Webpack`.
=> Add webpack

dict/brands.json
=> feat: add CodeSandbox

dict/softwares.json
=> Added tRPC

dict/brands.json
Add new brands to dictionary.
- `stackoverflow` - **Stack Overflow**
- `producthunt` - **Product Hunt**
=> Add Stack Overflow and Product Hunt

dict/softwares.json
=> feat: add ChatGPT

dict/brands.json
=> feat: add ByteDance

dict/softwares.json
=> feat: added CocoaPods

packages/case-police/dict/brands.json, packages/case-police/dict/products.json, packages/case-police/dict/softwares.json
- Cloudflare ( https://www.cloudflare.com/learning/what-is-cloudflare/ )
- CloudFront ( https://aws.amazon.com/cloudfront/ )
- YubiKey ( https://www.yubico.com/products/ )
=> feat: add Cloudflare, CloudFront, YubiKey

README.md
=> docs: update links to dict in README

packages/case-police/dict/general.json
=> feat: added IaC in `general.json`

packages/case-police/dict/brands.json
Hello,
I propose to add UnJS.
Related to https://github.com/unjs/website/pull/184#discussion_r1395771402
=> feat: add unjs to brands

packages/case-police/dict/softwares.json
=> feat: add premid to softwares

packages/case-police/dict/softwares.json
ref: https://www.typescriptlang.org/tsconfig#references
=> feat: add 1 words "TSConfig"

packages/case-police/dict/abbreviates.json
=> Add IoT (internet of things) to abbreviates list
